version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  api:
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - '3344:3000'
      - '8080:8080'
    links:
      - 'db'

  app:
    build: ./app
    volumes:
      - '/tmp:/tmp'
    environment:
      - NODE_ENV=production
    ports:
      - '8081:80'
